# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cliff < Formula
  desc "A terminal-native directory for CLIs and TUIs"
  homepage "https://cliff.sh"
  version "0.1.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.18/cliff_0.1.18_darwin_amd64.tar.gz"
      sha256 "c083d716239a522373ef9cb647c0a16bc15d131386bb3d2f8029fb5d3ea36ffa"

      define_method(:install) do
        bin.install "cliff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.18/cliff_0.1.18_darwin_arm64.tar.gz"
      sha256 "27c4f060befe41da86d4e4b2dc19b37a0d1881e516cd18bfb9f7c3672f54d70f"

      define_method(:install) do
        bin.install "cliff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.18/cliff_0.1.18_linux_amd64.tar.gz"
      sha256 "000a3dca4092e5f10c51a3b03d73fbc9cf9ab01e023ebed2a32ceeafe3a79b83"
      define_method(:install) do
        bin.install "cliff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.18/cliff_0.1.18_linux_arm64.tar.gz"
      sha256 "8353716e5699e91b02c66025001373318b3b397c52b7294a7f865148ed51be36"
      define_method(:install) do
        bin.install "cliff"
      end
    end
  end

  test do
    system "#{bin}/cliff", "--version"
  end
end
