# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cliff < Formula
  desc "A terminal-native directory for CLIs and TUIs"
  homepage "https://cliff.sh"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.5/cliff_0.1.5_darwin_amd64.tar.gz"
      sha256 "804adbfec28714b042a8d4365fc0ed7d80228afda4abe108590745d0a71df105"

      define_method(:install) do
        bin.install "cliff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.5/cliff_0.1.5_darwin_arm64.tar.gz"
      sha256 "be0ab5601e18dc3a5d9e45119943f0a9afb6a79fc0665ee195a20a851ded31df"

      define_method(:install) do
        bin.install "cliff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.5/cliff_0.1.5_linux_amd64.tar.gz"
      sha256 "6ec639ddffb762bdcf29bd1bd29dc54d4114b6cea7d4587437db616d736e4c5b"
      define_method(:install) do
        bin.install "cliff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmcntsh/cliff/releases/download/v0.1.5/cliff_0.1.5_linux_arm64.tar.gz"
      sha256 "c5f753ee5f78254d018c66d832aed4f74f683c8d62d77d7878b9d2d2d4ec72de"
      define_method(:install) do
        bin.install "cliff"
      end
    end
  end

  test do
    system "#{bin}/cliff", "--version"
  end
end
